name: First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
           echo "Hello World"
           echo "Welcome to GitHub Actions"
      - name: Print goodbye
        run: |
          echo "Good Bye"
          echo "See you next time"
